yarnPath: ".yarn/releases/yarn-berry.cjs"

# We'll keep the caches through for offline installs, but we'll yeeting da .pnp.cjs
# because we're switching to the old node_modules way
nodeLinker: node-modules
